# Generated by Django 5.2 on 2025-04-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gemini_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="image",
            field=models.FileField(upload_to=""),
        ),
        migrations.AlterField(
            model_name="report",
            name="report_text",
            field=models.TextField(null=True),
        ),
    ]
